CREATE TABLE IF NOT EXISTS staging.cleaned_data (
    "Row ID" INTEGER,
    "Order ID" TEXT,
    "Order Date" DATE,
    "Ship Date" DATE,
    "Ship Mode" TEXT,
    "Customer ID" TEXT,
    "Customer Name" TEXT,
    "Segment" TEXT,
    "Country" TEXT,
    "City" TEXT,
    "State" TEXT,
    "Postal Code" TEXT,
    "Region" TEXT,
    "Product ID" TEXT,
    "Category" TEXT,
    "Sub-Category" TEXT,
    "Product Name" TEXT,
    "Sales" NUMERIC,
    "Quantity" INTEGER,
    "Discount" NUMERIC,
    "Ship Duration" INTERVAL,
    "UnitPrice" NUMERIC
);