services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: DataStore360
      POSTGRES_USER: DataStore360
      POSTGRES_PASSWORD: notroot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: